#!/usr/bin/env bash
# Read the content of /etc/passwd line by line

while IFS=: read -r username user_id _ _ home_directory shell _; do
    # Display the user information in the required format
    echo "The user $username is part of the $user_id gang, lives in $home_directory and rides $shell. $user_id's place is protected by the passcode x, more info about the user here: $username"
done < /etc/passwd
