#!/usr/bin/env bash
# Read the content of /etc/passwd line by line

while IFS=: read -r username user_id _ _ home_directory shell _; do
    # Extract just the base name of the home directory
    home_base=$(basename "$home_directory")

    # Print the information in the desired format
    echo "The user $username is part of the x gang, lives in $home_base and rides $shell. x's place is protected by the passcode x, more info about the user here: $username"
done < /etc/passwd
